### ISSUE TITLE
Problem with socket.io version 3.0.0 and 3.0.1 and maybe more

### ISSUE THREAD

**Issue by swompythesecond** [IgnasKavaliauskas/SocketIO-GMS2-Extension#9]
In these Versions you will always get a cors policy error which says cross origin isn't allowed even if your server is local. A version that works perfectly fine is 2.3.0 im pretty sure other Version work aswell but thats a Version I really know works since I used it.

**Comment by ignoxx** [comment]
Thank you for reporting it :)

**Comment by MaddiFurr** [comment]
I'm also having this issue. Was going to being working on a project and couldn't get past this issue. I'm still doing some research, but so far I've had no luck.

I have found this issue to be present when I try to run the Node.JS server on a dedicated server rather than local host.

Here is what the browser developer console outputs when you try to connect to a different IP than 'localhost'

`Access to XMLHttpRequest at 'http://<ExternalServerIPHere>:42069/socket.io/?EIO=3&transport=polling&t=NPHJwSB' from origin 'http://127.0.0.1:51264' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

*EDIT 1*

I even tried to modify the 'index.js' file that holds the code to run the listener to try and force the listener to run like so `server.listen(PORT, "0.0.0.0", (err) => {`

The error is still present. Will continue researching to see if I find a solution.


Hope this can be fixed soon!
Thanks :)

**Comment by swompythesecond** [comment]
Which socket.io version are you using ? And you may have to use https and wws because some browsers like chrome block connection automatically if there not crypted. Which also leads to a cors error

**Comment by MaddiFurr** [comment]
I'm using version 2.3.0

I tried setting it to https to listen in the Game Maker Studio 2 client.

The browser I'm using is Brave, which is Chromium based, and even after trying to use https, it still doesn't want to connect.

I did install an openssl cert and changed the index.js code from the guide to include that, and im now getting this error

```Failed to load resource: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH```

I do have a self signed ssl certificate that I created to try and load for this project, and I can't seem to get it to connect still. I'm not the most experienced with Node.JS and so I wanted to use this to learn but I can't seem to get any further.

**Comment by ignoxx** [comment]
Hey guys, I managed to fix the CORS error by allowing it in the Backend itself. Check the sampleserver.js of Example 1

https://github.com/ignasKavaliauskas/SocketIO-GMS2-Extension/blob/f0a997d4773cc79e11a64e10f264b6eb7ecf93d8/Example/Example%201/sampleserver.js#L7

I've also updated the extension to[ v1.0.4, check the releases](https://github.com/ignasKavaliauskas/SocketIO-GMS2-Extension/releases/tag/v1.0.4) :)  

Let me know if this solves your issue.

**Comment by MaddiFurr** [comment]
I will check this out once I finish my move! Thanks :)
